# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

build:
  correctness:
    build:
      image: typedb-ubuntu-22.04
      command: |
        sudo apt-get update && sudo apt-get install -y libtinfo5
        if [ -n "${CARGO_BAZEL_GENERATOR_URL_LINUX_X86_64:-}" ] && [ -n "${CARGO_BAZEL_GENERATOR_SHA256_LINUX_X86_64:-}" ]; then
            export CARGO_BAZEL_GENERATOR_URL="$CARGO_BAZEL_GENERATOR_URL_LINUX_X86_64"
            export CARGO_BAZEL_GENERATOR_SHA256="$CARGO_BAZEL_GENERATOR_SHA256_LINUX_X86_64"
        fi
        bazel build //...
        bazel test $(bazel query 'kind(checkstyle_test, //... except tool/ide/...)') || exit 1
    validate-all-maven-deps-build:
      image: typedb-ubuntu-22.04
      command: |
        sudo apt-get update && sudo apt-get install -y libtinfo5
        git apply .factory/validate_all_maven_includes.patch
        bazel build @typedb_maven//...
    rust-ide-sync:
      image: typedb-ubuntu-22.04
      command: |
        if [ -n "${CARGO_BAZEL_GENERATOR_URL_LINUX_X86_64:-}" ] && [ -n "${CARGO_BAZEL_GENERATOR_SHA256_LINUX_X86_64:-}" ]; then
            export CARGO_BAZEL_GENERATOR_URL="$CARGO_BAZEL_GENERATOR_URL_LINUX_X86_64"
            export CARGO_BAZEL_GENERATOR_SHA256="$CARGO_BAZEL_GENERATOR_SHA256_LINUX_X86_64"
        fi
        cd tool/ide/test/
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=streamed || exit 1
        tool/ide/rust/verify.sh
    deploy-maven-snapshot:
      filter:
        owner: typedb
        branch: [ master, development ]
      image: typedb-ubuntu-22.04
      dependencies: [ build ]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run //tool/bazelinstall:remote_cache_setup.sh
        bazel run --define version=$(git rev-parse HEAD) //common/java:deploy-maven -- snapshot
    sync-dependencies:
      image: typedb-ubuntu-22.04
      filter:
        owner: typedb
        branch: [master, development]
      dependencies: [build]
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @typedb_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@${FACTORY_COMMIT}
